import {
  Column,
  CreateDateColumn,
  Entity,
  PrimaryGeneratedColumn,
  UpdateDateColumn,
} from 'typeorm';

/**
 * "Bancos" — histórico de operaciones bancarias. A task the Admin/Employer must
 * order with their bank (cobros = collections, pagos = payments), generated by
 * the month-end close or by manual selection of Facturas/Comisiones/Salarios.
 */
@Entity('cjobs_bank_operations')
export class BankOperation {
  @PrimaryGeneratedColumn('increment', { type: 'bigint' })
  id: number;

  @Column({ name: 'public_id', type: 'uuid', unique: true, default: () => 'uuid_generate_v4()' })
  publicId: string;

  /** 'ADMIN' (platform-level) or 'EMPLOYER' (a single employer's book). */
  @Column({ name: 'scope_type', type: 'varchar', length: 20 })
  scopeType: 'ADMIN' | 'EMPLOYER';

  @Column({ name: 'employer_id', type: 'bigint', nullable: true })
  employerId: number | null;

  /** Which tab: FACTURAS | COMISIONES (admin) | SALARIOS (employer). */
  @Column({ name: 'tab', type: 'varchar', length: 20 })
  tab: 'FACTURAS' | 'COMISIONES' | 'SALARIOS';

  /** COBRO = collect from clients/employers, PAGO = pay partners/workers. */
  @Column({ name: 'kind', type: 'varchar', length: 10 })
  kind: 'COBRO' | 'PAGO';

  @Column({ name: 'period_start', type: 'date' })
  periodStart: string;

  @Column({ name: 'period_end', type: 'date' })
  periodEnd: string;

  @Column({ name: 'item_count', type: 'int', default: 0 })
  itemCount: number;

  @Column({ name: 'total_amount', type: 'numeric', precision: 12, scale: 2, default: 0 })
  totalAmount: string;

  /** AUTO = month-end close, MANUAL = user selection. */
  @Column({ name: 'source', type: 'varchar', length: 10, default: 'MANUAL' })
  source: 'AUTO' | 'MANUAL';

  /** PENDING = awaiting the user to order it with the bank; DONE = ordered. */
  @Column({ name: 'status', type: 'varchar', length: 20, default: 'PENDING' })
  status: 'PENDING' | 'DONE';

  @Column({ name: 'ref_ids', type: 'jsonb', nullable: true })
  refIds: string[] | null;

  @Column({ name: 'notes', type: 'text', nullable: true })
  notes: string | null;

  @Column({ name: 'done_at', type: 'timestamptz', nullable: true })
  doneAt: Date | null;

  @CreateDateColumn({ name: 'created_at', type: 'timestamptz' })
  createdAt: Date;

  @UpdateDateColumn({ name: 'updated_at', type: 'timestamptz' })
  updatedAt: Date;
}
